# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "9292:9292"
    environment:
      RACK_ENV: production
      DB_Username: user
      DB_Password: password
      DB_Port: 5555
    depends_on:
      db:
        restart: true
        condition: service_healthy

  db:
   image: postgres:17-alpine
   expose: ["5555"]
   volumes:
      - data:/var/lib/postgresql/data
   restart: unless-stopped
   environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      PGPORT: 5555
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
     interval: 10s
     retries: 5
     start_period: 30s
     timeout: 10s

volumes:
  data:
